runtime: python39
service: py
entrypoint: python app.py
env_variables:
  GCP_DEV: yes
automatic_scaling:
  max_instances: 1
runtime_config:
  python_version: 3.9
  requirements_path: requirements.txt
